version: '3.9'

name: com_base
services:
  joomla_php8:
    image: joomla:3.10.11
    restart: always
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - 80:80
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_NAME: ${JOOMLA_DB_NAME}
      JOOMLA_DB_USER: ${JOOMLA_DB_USER}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD}
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/zphp.ini
      # - ./component/admin:/var/www/html/administrator/components/com_base
      # - ./component/site:/var/www/html/components/com_base
      - joomla3_files:/var/www/html
    
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${JOOMLA_DB_NAME}
      - MYSQL_USER=${JOOMLA_DB_USER}
      - MYSQL_PASSWORD=${JOOMLA_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${JOOMLA_DB_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - com_base_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${JOOMLA_DB_USER}
      - PMA_PASSWORD=${JOOMLA_DB_PASSWORD}

volumes:
  com_base_db:
  joomla3_files: